use std::borrow::Cow;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use super::WalColors;

/// Get pywal cache directory.
pub fn wal_cache_dir() -> PathBuf {
    crate::utils::cache_dir()
        .unwrap_or_else(|| PathBuf::from("/tmp"))
        .join("wal")
}

/// Export colors to the pywal cache directory.
pub fn export_colors(colors: &WalColors) -> Result<PathBuf> {
    let cache_dir = wal_cache_dir();
    export_colors_to(&cache_dir, colors)?;
    Ok(cache_dir)
}

pub(crate) fn export_colors_to(cache_dir: &Path, colors: &WalColors) -> Result<()> {
    fs::create_dir_all(cache_dir).context("Failed to create wal cache directory")?;

    write_json_export(&cache_dir.join("colors.json"), colors)?;
    write_text_export(&cache_dir.join("colors"), plain_colors(colors))?;
    write_text_export(&cache_dir.join("colors.sh"), shell_colors(colors))?;
    write_text_export(
        &cache_dir.join("colors.Xresources"),
        xresources_colors(colors),
    )?;

    Ok(())
}

fn write_json_export(path: &Path, colors: &WalColors) -> Result<()> {
    let file =
        fs::File::create(path).with_context(|| format!("Failed to create {}", path.display()))?;
    serde_json::to_writer_pretty(std::io::BufWriter::new(file), colors)
        .with_context(|| format!("Failed to write {}", path.display()))
}

fn write_text_export(path: &Path, contents: String) -> Result<()> {
    fs::write(path, contents).with_context(|| format!("Failed to write {}", path.display()))
}

fn plain_colors(colors: &WalColors) -> String {
    let palette = colors.colors.entries();
    let mut plain = palette.as_slice().join("\n");
    plain.push('\n');
    plain
}

fn shell_colors(colors: &WalColors) -> String {
    let palette = colors.colors.entries();
    let wallpaper = shell_escape(&colors.wallpaper);
    let mut sh = String::from("# Shell variables\n# Generated by FrostWall\n");

    let _ = writeln!(sh, "wallpaper='{wallpaper}'");
    let _ = writeln!(sh, "background='{}'", colors.special.background);
    let _ = writeln!(sh, "foreground='{}'", colors.special.foreground);
    let _ = writeln!(sh, "cursor='{}'", colors.special.cursor);

    for (index, color) in palette.iter().enumerate() {
        let _ = writeln!(sh, "color{index}='{color}'");
    }

    sh
}

fn xresources_colors(colors: &WalColors) -> String {
    let palette = colors.colors.entries();
    let mut xres = String::from("! X colors\n! Generated by FrostWall\n");

    let _ = writeln!(xres, "*background: {}", colors.special.background);
    let _ = writeln!(xres, "*foreground: {}", colors.special.foreground);
    let _ = writeln!(xres, "*cursorColor: {}", colors.special.cursor);

    for (index, color) in palette.iter().enumerate() {
        let _ = writeln!(xres, "*color{index}: {color}");
    }

    xres
}

fn shell_escape(value: &str) -> Cow<'_, str> {
    if value.contains('\'') {
        Cow::Owned(value.replace('\'', "'\\''"))
    } else {
        Cow::Borrowed(value)
    }
}
